name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/osrm-backend-k8s:latest

    - name: Ending log
      run: echo "Docker image pushed to Docker Hub"
